### ISSUE TITLE
[Ask]: mm strategy

### ISSUE THREAD

**Issue by thorjeus** [hmmdeif/the-professor#3]
hi, 
how to make this app run as conventional market maker? 
by ignoring the strategy, let's say the bb strat and just use the position range which move constantly according to current price?

using bb strat (maybe only on my side) the positions sometimes stacked at one price at the top, even the parameter on bb stats already changed.

appreciate for any information.
thanks & regards.

**Comment by hmmdeif** [comment]
Just change the `placeOrder` function calls in `candleDataReceived` for the strategy to your ideal MM risk. Something like:

```
  public async candleDataReceived(resolution: number, multiplier: number, orderHistoryCall: boolean, data: any) {
    this.placeOrder(instrument.ask + 1, 10000, Direction.sell)
    this.placeOrder(instrument.bid - 1, 10000, Direction.buy)
  }
```

**Comment by thorjeus** [comment]
beautiful work, thank you so much.
